
import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import RegisterPage from "../components/RegisterForm";



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>freeCodeCamp Survey Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterPage />
    
    </div>
  )
}

export default Home;